/** Client must never supply identity, plan, or financial facts to Ask Klaro. */
export const BANNED_AI_CHAT_BODY_KEYS = [
  'user_id',
  'userId',
  'plan',
  'plan_name',
  'isPro',
  'income',
  'expenses',
  'netFlow',
  'budget',
  'categories',
  'topSpendingCategories',
  'goals',
  'assets',
  'liabilities',
  'netWorth',
  'context',
  'financialContext',
  'observationSeeds',
  'contextHash',
  'transactions',
  'history',
  'messages',
  'systemPrompt',
  'resolved_state',
  'resolvedState',
  'dialogueState',
  'resolvedOperation',
  'intent',
] as const
