-- Founder Support Inbox (Mission Control).
-- Additive and backward compatible: the user submission flow (/api/support) is unchanged
-- and the original request message on support_requests is never modified.
--
-- 1. support_requests lifecycle: updated_at (last activity), resolved_at, resolved_by,
--    and a status check limited to 'open' | 'resolved' (every existing row is 'open').
--
-- 2. public.support_request_messages
--    Founder replies, one row per reply. The id is generated by the founder's composer
--    and doubles as the duplicate-send guard: a reply is claimed ('pending') before the
--    email is sent and marked 'sent' or 'failed' afterwards.
--    Service role only: RLS enabled with no policies.

ALTER TABLE public.support_requests
  ADD COLUMN IF NOT EXISTS updated_at timestamptz,
  ADD COLUMN IF NOT EXISTS resolved_at timestamptz,
  ADD COLUMN IF NOT EXISTS resolved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL;

UPDATE public.support_requests
SET updated_at = coalesce(created_at, now())
WHERE updated_at IS NULL;

ALTER TABLE public.support_requests
  ALTER COLUMN updated_at SET DEFAULT now(),
  ALTER COLUMN updated_at SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'support_requests_status_check') THEN
    ALTER TABLE public.support_requests
      ADD CONSTRAINT support_requests_status_check CHECK (status IN ('open', 'resolved'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.support_request_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  support_request_id uuid NOT NULL REFERENCES public.support_requests(id) ON DELETE CASCADE,
  sender_type text NOT NULL CHECK (sender_type IN ('user', 'founder')),
  sender_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  body text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 5000),
  delivery_status text NOT NULL DEFAULT 'pending' CHECK (delivery_status IN ('pending', 'sent', 'failed')),
  email_message_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS support_request_messages_request_idx
  ON public.support_request_messages (support_request_id, created_at);

COMMENT ON TABLE public.support_request_messages IS
  'Founder replies to support requests and their email delivery state. Service role only.';

ALTER TABLE public.support_request_messages ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.support_request_messages FROM anon, authenticated;
